using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.MachineLinking.UI;

[GenerateTypedNameReferences]
public sealed partial class StopWatchWindow : DefaultWindow
{
    [Dependency] private IGameTiming _timing = default!;

    private TimeSpan? _triggerTime;

    private TimeSpan _accumulated = TimeSpan.Zero;

    private bool _stopwatchRunning;

    public event Action? OnStartStopwatch;

    public event Action? OnStopStopwatch;

    public event Action? OnResetStopwatch;

    public StopWatchWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleTimer.OnPressed += ToggleTimerOnOnPressed;
        ResetTimer.OnPressed += ResetTimerOnOnPressed;
    }

    private void ResetTimerOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        // Reset accumulated time and trigger time. If running, restart from now.
        _accumulated = TimeSpan.Zero;

        if (_stopwatchRunning)
        {
            _triggerTime = _timing.CurTime;
        }
        else
        {
            _triggerTime = null;
        }

        CurrentTime.Text = FormatElapsed(TimeSpan.Zero);
        OnResetStopwatch?.Invoke();
    }

    private void ToggleTimerOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (!_stopwatchRunning)
        {
            // Start or resume
            _triggerTime = _timing.CurTime;
            _stopwatchRunning = true;
            ToggleTimer.Text = Loc.GetString("Stop");
            OnStartStopwatch?.Invoke();
        }
        else
        {
            // Pause/stop: accumulate elapsed since trigger
            if (_triggerTime != null)
            {
                _accumulated += _timing.CurTime - _triggerTime.Value;
            }

            _triggerTime = null;
            _stopwatchRunning = false;
            ToggleTimer.Text = Loc.GetString("Start");
            CurrentTime.Text = FormatElapsed(_accumulated);
            OnStopStopwatch?.Invoke();
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Update the displayed time every frame when running or when paused for a final display refresh
        var elapsed = _accumulated;
        if (_stopwatchRunning && _triggerTime != null)
        {
            var delta = _timing.CurTime - _triggerTime.Value;
            if (delta > TimeSpan.Zero)
                elapsed += delta;
        }

        CurrentTime.Text = FormatElapsed(elapsed);
    }

    private static string FormatElapsed(TimeSpan elapsed)
    {
        if (elapsed < TimeSpan.Zero)
            elapsed = TimeSpan.Zero;

        var minutes = (int)elapsed.TotalMinutes;
        var seconds = elapsed.Seconds;
        return $"{minutes:D2}:{seconds:D2}";
    }

    public TimeSpan? TriggerTime
    {
        get => _triggerTime;
        set => _triggerTime = value;
    }

    public TimeSpan Accumulated
    {
        get => _accumulated;
        set => _accumulated = value;
    }

    public bool StopwatchRunning
    {
        get => _stopwatchRunning;
        set => _stopwatchRunning = value;
    }
}

